version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: blogpost-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: blog_post_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - '3307:3306'
    networks:
      - app-network
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: blogpost-backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: appuser
      DB_PASSWORD: apppassword
      DB_NAME: blog_post_db
    ports:
      - '3333:3333'
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: blogpost-frontend
    restart: always
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_BASE_URL: 'http://blogpost-backend:3333'
    ports:
      - '3000:3000'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
